name: Unit Test

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master,release/* ]

jobs:
  run-unit-test:
    name: Run unit test and coverage
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout code
        uses: actions/checkout@v2
      - name: install lcov
        run: sudo apt-get install -y lcov
      - name: Setup flutter
        # uses: actions/setup-java@v1
        # with:
        #   java-version: '12.x'
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: install dependenies.
        run: flutter pub get
      - name: add dummy config.
        run: echo "class AppConfig {  static String get userBaseURL {    return 'http://localhost:4000';  } static String get coreURL {    return 'http://localhost:4000';  }  static String clientId = 'something';  static String clientSecret = 'here';}">./lib/app_config.dart
      - name: Run unit test.
        run: flutter test --coverage
      - name: remove app_config.dart
        run: lcov --remove coverage/lcov.info 'lib/app_config.dart' -o coverage/lcov.info
      - name: Upload coverage to Codecov 
        uses: codecov/codecov-action@v1 
        with: 
          token: ${{ secrets.CODECOV_TOKEN }} 
          file: coverage/lcov.info 
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage/lcov.info